apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: null
spec:
  addonComponents:
    kiali:
      enabled: true
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 6
          minReplicas: 3
        serviceAnnotations:
          cloud.google.com/app-protocols: '{"https":"HTTP2","http":"HTTP"}'
          cloud.google.com/backend-config: '{"default": "istio-neg"}'
          cloud.google.com/neg: '{"ingress": true}'
      name: istio-ingressgateway
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2
        strategy:
          rollingUpdate:
            maxUnavailable: 1
  values:
    gateways:
      istio-ingressgateway:
        podAntiAffinityTermLabelSelector:
        - key: app
          operator: In
          topologyKey: failure-domain.beta.kubernetes.io/zone
          values: istio-egressgateway
          weight: 100
        - key: app
          operator: In
          topologyKey: kubernetes.io/hostname
          values: istio-egressgateway
          weight: 50
        ports:
        - name: http-status-port
          port: 15020
          targetPort: 15020
        - name: http2
          nodePort: 31380
          port: 80
          targetPort: 80
        - name: https
          nodePort: 31390
          port: 443
          targetPort: 443
        - name: tcp
          nodePort: 31400
          port: 31400
        - name: https-kiali
          port: 15029
          targetPort: 15029
        - name: https-prometheus
          port: 15030
          targetPort: 15030
        - name: https-grafana
          port: 15031
          targetPort: 15031
        - name: https-tracing
          port: 15032
          targetPort: 15032
        - name: tls
          port: 15443
          targetPort: 15443
        sds:
          enabled: true
        type: NodePort
    global:
      proxy:
        includeIPRanges: 10.0.0.0/8
    meshConfig:
      accessLogFile: "/dev/stdout"
      accessLogEncoding: "JSON"
    kiali:
      dashboard:
        auth:
          strategy: anonymous
        grafanaURL: https://dash.e-conomic.net/
      security:
        enabled: false
    pilot:
      podAntiAffinityLabelSelector:
      - key: istio
        operator: In
        topologyKey: failure-domain.beta.kubernetes.io/zone
        values: pilot
    tracing:
      enabled: true
      jaeger:
        memory:
          max_traces: 10000

