gateways:
  istio-ingressgateway:
    ports:
    - port: 15020
      targetPort: 15020
      name: http-status-port
    - port: 80
      targetPort: 80
      name: http2
      nodePort: 31380
    - port: 443
      name: https
      nodePort: 31390
    - port: 31400
      name: tcp
      nodePort: 31400
    - port: 15029
      targetPort: 15029
      name: https-kiali
    - port: 15030
      targetPort: 15030
      name: https-prometheus
    - port: 15031
      targetPort: 15031
      name: https-grafana
    - port: 15032
      targetPort: 15032
      name: https-tracing
    - port: 15443
      targetPort: 15443
      name: tls
    sds:
      enabled: true
    autoscaleMin: 3
    autoscaleMax: 6
    type: NodePort
    serviceAnnotations:
      cloud.google.com/app-protocols: '{"https":"HTTP2","http":"HTTP"}'
      beta.cloud.google.com/backend-config: '{"default": "istio-neg"}'
      cloud.google.com/neg: '{"ingress": true}'
    podAntiAffinityTermLabelSelector:
      - key: app
        operator: In
        values: istio-egressgateway
        topologyKey: "failure-domain.beta.kubernetes.io/zone"
        weight: 100
      - key: app
        operator: In
        values: istio-egressgateway
        topologyKey: "kubernetes.io/hostname"
        weight: 50

pilot:
  autoscaleMin: 2
  autoscaleMax: 3
  rollingMaxUnavailable: 1
  podAntiAffinityLabelSelector:
    - key: istio
      operator: In
      values: pilot
      topologyKey: failure-domain.beta.kubernetes.io/zone

tracing:
  enabled: true
  jaeger:
    memory:
      max_traces: 10000

kiali:
  enabled: true
  dashboard:
    auth:
      strategy: anonymous
    grafanaURL: https://dash.e-conomic.net/
  security:
    enabled: false
global:
  proxy:
    includeIPRanges: "10.0.0.0/8"
