apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
spec:
  template:
    spec:
      volumes:
      - name: envoy-descriptor
        configMap:
          name: envoy-descriptor
      - $patch: add
