apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: null
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 6
          minReplicas: 3
        serviceAnnotations:
          cloud.google.com/app-protocols: '{"https":"HTTP2","http":"HTTP"}'
          cloud.google.com/backend-config: '{"default": "edge-ingress"}'
          cloud.google.com/neg: '{"ingress": true}'
    - name: iap-ingressgateway
      enabled: true
      label:
        app: iap-ingressgateway
        istio: iap-ingressgateway
      k8s:
        hpaSpec:
          maxReplicas: 6
          minReplicas: 3
        serviceAnnotations:
          cloud.google.com/app-protocols: '{"https":"HTTP2","http":"HTTP"}'
          cloud.google.com/backend-config: '{"default": "istio-iap"}'
          cloud.google.com/neg: '{"ingress": true}'
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2
        strategy:
          rollingUpdate:
            maxUnavailable: 1
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      proxy:
        includeIPRanges: 10.0.0.0/8
    meshConfig:
      accessLogFile: "/dev/stdout"
      accessLogEncoding: "JSON"

